_translation_webui:
    resource: "@TranslationBundle/Resources/config/routing_webui.yml"
    prefix:  /admin
    options: { i18n: false }
  
_translation_profiler:
    resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yml'
    options: { i18n: false }
