<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.service.translation' shared service.

include_once $this->targetDirs[3].'/vendor/a2lix/translation-form-bundle/TranslationForm/TranslationFormInterface.php';
include_once $this->targetDirs[3].'/vendor/a2lix/translation-form-bundle/TranslationForm/TranslationForm.php';

return $this->privates['a2lix_translation_form.default.service.translation'] = new \A2lix\TranslationFormBundle\TranslationForm\TranslationForm(($this->privates['form.registry'] ?? $this->load('getForm_RegistryService.php')), ($this->services['doctrine'] ?? $this->getDoctrineService()));
