<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.sitemap' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/Sitemap.php';

return $this->services['app.sitemap'] = new \App\Service\Sitemap($this);
