<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.type.translationsLocalesSelector' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/a2lix/translation-form-bundle/Form/Type/TranslationsLocalesSelectorType.php';
include_once $this->targetDirs[3].'/vendor/a2lix/translation-form-bundle/Locale/LocaleProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/a2lix/translation-form-bundle/Locale/DefaultProvider.php';

return $this->privates['a2lix_translation_form.default.type.translationsLocalesSelector'] = new \A2lix\TranslationFormBundle\Form\Type\TranslationsLocalesSelectorType(($this->privates['a2lix_translation_form.default.service.parameter_locale_provider'] ?? ($this->privates['a2lix_translation_form.default.service.parameter_locale_provider'] = new \A2lix\TranslationFormBundle\Locale\DefaultProvider($this->parameters['a2lix_translation_form.locales'], 'nl', $this->parameters['a2lix_translation_form.locales']))));
