<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fm_elfinder.loader' shared service.

include_once $this->targetDirs[3].'/vendor/helios-ag/fm-elfinder-bundle/Loader/ElFinderLoader.php';
include_once $this->targetDirs[3].'/vendor/helios-ag/fm-elfinder-bundle/Model/ElFinderConfigurationProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/helios-ag/fm-elfinder-bundle/Configuration/ElFinderConfigurationReader.php';

return $this->services['fm_elfinder.loader'] = new \FM\ElfinderBundle\Loader\ElFinderLoader(new \FM\ElfinderBundle\Configuration\ElFinderConfigurationReader($this->parameters['fm_elfinder'], ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), $this));
