<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'isometriks_spam.form.extension.type.honeypot' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/vendor/isometriks/spam-bundle/Form/Extension/Spam/Type/FormTypeHoneypotExtension.php';

return $this->privates['isometriks_spam.form.extension.type.honeypot'] = new \Isometriks\Bundle\SpamBundle\Form\Extension\Spam\Type\FormTypeHoneypotExtension(($this->services['translator'] ?? $this->getTranslatorService()), 'validators', ['field' => 'email_address', 'use_class' => false, 'hide_class' => 'hidden', 'global' => false, 'message' => 'Form fields are invalid']);
