<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translation.cache_clearer' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Service/CacheClearer.php';
include_once $this->targetDirs[3].'/vendor/symfony/filesystem/Filesystem.php';

return $this->services['php_translation.cache_clearer'] = new \Translation\Bundle\Service\CacheClearer($this->targetDirs[0], ($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())));
