<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translation.storage_manager' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Service/StorageManager.php';

$this->services['php_translation.storage_manager'] = $instance = new \Translation\Bundle\Service\StorageManager();

$instance->addStorage('app', ($this->services['php_translation.storage.app'] ?? $this->load('getPhpTranslation_Storage_AppService.php')));

return $instance;
