<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'php_translation.configuration.app' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Model/Configuration.php';

return $this->privates['php_translation.configuration.app'] = new \Translation\Bundle\Model\Configuration(['dirs' => [0 => ($this->targetDirs[3].'/templates'), 1 => ($this->targetDirs[3].'/src')], 'output_dir' => ($this->targetDirs[3].'/translations'), 'excluded_names' => [0 => '*TestCase.php', 1 => '*Test.php'], 'excluded_dirs' => [0 => 'cache', 1 => 'data', 2 => 'logs'], 'external_translations_dirs' => [], 'output_format' => 'xlf', 'blacklist_domains' => [], 'whitelist_domains' => [], 'remote_storage' => [], 'local_storage' => [0 => 'php_translation.local_file_storage.abstract'], 'xliff_version' => '2.0', 'local_file_storage_options' => [], 'project_root' => $this->targetDirs[3], 'name' => 'app', 'locales' => $this->parameters['php_translation.locales']]);
