<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translation.catalogue_writer' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Catalogue/CatalogueWriter.php';

return $this->services['php_translation.catalogue_writer'] = new \Translation\Bundle\Catalogue\CatalogueWriter(($this->privates['translation.writer'] ?? $this->load('getTranslation_WriterService.php')), 'nl');
