<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translator.console.delete_obsolete' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Command/BundleTrait.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Command/DeleteObsoleteCommand.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Catalogue/CatalogueManager.php';

$this->services['php_translator.console.delete_obsolete'] = $instance = new \Translation\Bundle\Command\DeleteObsoleteCommand(($this->services['php_translation.storage_manager'] ?? $this->load('getPhpTranslation_StorageManagerService.php')), ($this->services['php_translation.configuration_manager'] ?? $this->load('getPhpTranslation_ConfigurationManagerService.php')), ($this->services['php_translation.catalogue_manager'] ?? ($this->services['php_translation.catalogue_manager'] = new \Translation\Bundle\Catalogue\CatalogueManager())), ($this->services['php_translation.catalogue_fetcher'] ?? $this->load('getPhpTranslation_CatalogueFetcherService.php')));

$instance->setName('translation:delete-obsolete');

return $instance;
