<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'slot_mandrill.dispatcher' shared service.

include_once $this->targetDirs[3].'/vendor/slot/mandrill-bundle/Slot/MandrillBundle/Dispatcher.php';
include_once $this->targetDirs[3].'/vendor/mandrill/mandrill/src/Mandrill.php';

return $this->services['slot_mandrill.dispatcher'] = new \Slot\MandrillBundle\Dispatcher(($this->services['slot_mandrill.client'] ?? ($this->services['slot_mandrill.client'] = new \Mandrill('---'))), 'robbertluit@hotmail.com', 'Robbert', 'Robbert', false, $this->parameters['slot_mandrill.proxy'], false);
