<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.in_memory' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/InMemoryUserProvider.php';

return $this->privates['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(['robbert' => ['password' => 'XSJZ99982', 'roles' => [0 => 'ROLE_ADMIN', 1 => 'ROLE_SUPER_ADMIN']], 'alessandro' => ['password' => 'XSJZ99982', 'roles' => [0 => 'ROLE_ADMIN', 1 => 'ROLE_SUPER_ADMIN']]]);
