slot_mandrill:
    api_key: "---"
    default:
        sender: "robbertluit@hotmail.com"
        sender_name: "Robbert"
        subaccount: "Robbert"

services:
    slot_mandrill.client:
        public: true
        class: "%slot_mandrill.client.class%"
        arguments: ["%slot_mandrill.api_key%"]
    slot_mandrill.dispatcher:
        public: true
        class: "%slot_mandrill.dispatcher.class%"
        arguments: ["@slot_mandrill.client", "%slot_mandrill.default.sender%", "%slot_mandrill.default.sender_name%", "%slot_mandrill.default.subaccount%", "%slot_mandrill.disable_delivery%", "%slot_mandrill.proxy%", "%slot_mandrill.debug%"]
