<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'a2lix_translation_form.default.type.translationsFields' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/vendor/a2lix/translation-form-bundle/Form/Type/TranslationsFieldsType.php';

return $this->privates['a2lix_translation_form.default.type.translationsFields'] = new \A2lix\TranslationFormBundle\Form\Type\TranslationsFieldsType();
