<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translator.console.download' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Command/BundleTrait.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Command/DownloadCommand.php';

$this->services['php_translator.console.download'] = $instance = new \Translation\Bundle\Command\DownloadCommand(($this->services['php_translation.storage_manager'] ?? $this->load('getPhpTranslation_StorageManagerService.php')), ($this->services['php_translation.configuration_manager'] ?? $this->load('getPhpTranslation_ConfigurationManagerService.php')), ($this->services['php_translation.cache_clearer'] ?? $this->load('getPhpTranslation_CacheClearerService.php')));

$instance->setName('translation:download');

return $instance;
