<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translation.catalogue_fetcher' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Catalogue/CatalogueFetcher.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Reader/TranslationReaderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Reader/TranslationReader.php';

return $this->services['php_translation.catalogue_fetcher'] = new \Translation\Bundle\Catalogue\CatalogueFetcher(($this->privates['translation.reader'] ?? ($this->privates['translation.reader'] = new \Symfony\Component\Translation\Reader\TranslationReader())));
