<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translation.configuration_manager' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Service/ConfigurationManager.php';

$this->services['php_translation.configuration_manager'] = $instance = new \Translation\Bundle\Service\ConfigurationManager();

$instance->addConfiguration('app', ($this->privates['php_translation.configuration.app'] ?? $this->load('getPhpTranslation_Configuration_AppService.php')));

return $instance;
