<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'php_translation.storage.xlf_loader' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/translation/Loader/LoaderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/translation/Loader/XliffFileLoader.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-storage/src/Loader/XliffLoader.php';

return $this->privates['php_translation.storage.xlf_loader'] = new \Translation\SymfonyStorage\Loader\XliffLoader();
