<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translation.importer' shared service.

include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Service/Importer.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Extractor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/FileExtractor/FileExtractor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/FileExtractor/PHPFileExtractor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Visitor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/BaseVisitor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/BasePHPVisitor.php';
include_once $this->targetDirs[3].'/vendor/nikic/php-parser/lib/PhpParser/NodeVisitor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/ContainerAwareTrans.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/ContainerAwareTransChoice.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FlashMessage.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/AbstractFormType.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTrait.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTypeChoices.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTypeEmptyValue.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTypeInvalidMessage.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTypeLabelExplicit.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTypeLabelImplicit.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/FormTypePlaceholder.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/Symfony/ValidationAnnotation.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Php/SourceLocationContainerVisitor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/FileExtractor/TwigFileExtractor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Twig/Visitor/DummyTwigVisitor.php';
include_once $this->targetDirs[3].'/vendor/php-translation/extractor/src/Visitor/Twig/TwigVisitorFactory.php';

$a = new \Translation\Extractor\Extractor();

$b = new \Translation\Extractor\FileExtractor\PHPFileExtractor();

$c = new \Translation\Extractor\Visitor\Php\Symfony\FormTypeChoices();
$c->setSymfonyMajorVersion(4);

$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\ContainerAwareTrans());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\ContainerAwareTransChoice());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\FlashMessage());
$b->addVisitor($c);
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\FormTypeEmptyValue());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\FormTypeInvalidMessage());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\FormTypeLabelExplicit());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\FormTypeLabelImplicit());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\FormTypePlaceholder());
$b->addVisitor(new \Translation\Extractor\Visitor\Php\Symfony\ValidationAnnotation(($this->services['validator'] ?? $this->getValidatorService())));
$b->addVisitor(new \Translation\Extractor\Visitor\Php\SourceLocationContainerVisitor());
$d = ($this->services['twig'] ?? $this->getTwigService());

$e = new \Translation\Extractor\FileExtractor\TwigFileExtractor($d);
$e->addVisitor((new \Translation\Extractor\Visitor\Twig\TwigVisitorFactory())->create());

$a->addFileExtractor($b);
$a->addFileExtractor($e);

return $this->services['php_translation.importer'] = new \Translation\Bundle\Service\Importer($a, $d);
