<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'php_translator.console.sync' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/php-translation/symfony-bundle/Command/SyncCommand.php';

$this->services['php_translator.console.sync'] = $instance = new \Translation\Bundle\Command\SyncCommand(($this->services['php_translation.storage_manager'] ?? $this->load('getPhpTranslation_StorageManagerService.php')));

$instance->setName('translation:sync');

return $instance;
