<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXELgzOX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXELgzOX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXELgzOX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXELgzOX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXELgzOX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XELgzOX',
    'container.build_id' => '5c4b6527',
    'container.build_time' => 1550176439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXELgzOX');
