index:
    path: /
    defaults: { _controller: 'App\Controller\ClientController::index' }

client:
    path: /clients
    defaults: { _controller: 'App\Controller\ClientController::overview' }

account_manager:
    path: /account-manager
    defaults: { _controller: 'App\Controller\ClientController::index' }

client_detail:
    path: /{name}/detail/{id}
    defaults: { _controller: 'App\Controller\ClientController::index', name: null, id: null }

client_timeline:
    path: /my-timeline
    defaults: { _controller: 'App\Controller\ClientController::index' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\SecurityController::logout' }
