index:
    path: /
    defaults: { _controller: 'App\Controller\CategoryController::index' }

login:
    path: /login
    defaults: { _controller: 'App\Controller\SecurityController::login' }

logout:
    path: /logout
    defaults: { _controller: 'App\Controller\SecurityController::logout' }
