services:
    app.admin.blocks:
        class: App\Admin\CustomerAdmin
        arguments: [~, App\Entity\Customer,  SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Klanten', label: 'Persoon', icon: '<i class="fa fa-user"></i>', show_in_dashboard: true }
        public: true

    app.admin.appointment:
        class: App\Admin\AppointmentAdmin
        arguments: [~, App\Entity\Appointment,  SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Klanten', label: 'Afspraken', icon: '<i class="fa fa-user"></i>', show_in_dashboard: true }
        public: true

    app.admin.chattext:
        class: App\Admin\ChattextAdmin
        arguments: [~, App\Entity\Chattext,  SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Klanten', label: 'Chat tekst', icon: '<i class="fa fa-user"></i>', show_in_dashboard: false }
        public: true

    app.admin.happenings:
        class: App\Admin\HappeningAdmin
        arguments: [~, App\Entity\Happening,  SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Klanten', label: 'Gebeurtenissen', icon: '<i class="fa fa-user"></i>', show_in_dashboard: true }
        public: true
