imports:
- { resource: services_sonata.yaml }

parameters:
    locale: nl

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.config:
        class: 'App\Service\Config'
        arguments: ['@service_container']
        public: true

    app.referer:
        class: 'App\Service\Referer'
        arguments: ['@request_stack']
        public: true

    app.sitemap:
        class: 'App\Service\Sitemap'
        arguments: ['@service_container']
        public: true

    app.event_listener:
        class: 'App\Service\EventListener'
        arguments: ['@service_container']
        tags:
        - { name: kernel.event_listener, event: kernel.request }
        - { name: kernel.event_listener, event: kernel.response }
        - { name: kernel.event_listener, event: kernel.exception }
        public: true