_translation_edit_in_place:
    resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yml'
    prefix:  /admin
    options: { i18n: false }

_translation_webui:
    resource: "@TranslationBundle/Resources/config/routing_webui.yml"
    prefix:  /admin
    options: { i18n: false }

_translation_profiler:
    resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yml'
    options: { i18n: false }